POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{
    "userName": "johnygood",
    "mail": "johnygood@gmail.com",
    "passWord": "johnygood"
    
}

###
GET http://localhost:3000/customers/611b630aaf11851a30e640c6 HTTP/1.1

###
GET http://localhost:3000/customers HTTP/1.1
###
PATCH http://localhost:3000/customers/5ac1bcf6-7d72-4615-be0c-3c5f7906a553 HTTP/1.1

{
    "name": "Ajda" 
}
###

POST http://localhost:3000/customers/611d8e0b99f51d0be858cb3e/bookings HTTP/1.1
Content-Type: application/json

{
    "fitnessCenterId" : "611e33eb5af671354102a51a"
}



###
DELETE http://localhost:3000/customers/611a406b20e9c84aea739a26 HTTP/1.1


###

POST http://localhost:3000/fitnessCenters HTTP/1.1
content-type: application/json

{
     "name": "McFIT" ,
    "phoneNum": "12344545" ,
    "location": "Ankara" 
}

###
POST http://localhost:3000/fitnessCenters/611e33eb5af671354102a51a/rate HTTP/1.1
content-type: application/json

{
    "customerId": "611d8e0b99f51d0be858cb3e" ,
    "point": "10" ,
    "comment": "Cok kaliteli ve egitmenler ilgili"
}


###
DELETE http://localhost:3000/fitnessCenters/61181ff1d87e3f52274abedf HTTP/1.1
